name: System Tests

on:
  push:
    paths:
      - "version.txt"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: taskapi
          POSTGRES_USER: taskapi
          POSTGRES_PASSWORD: taskapi
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U taskapi"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Start MinIO
        run: |
          docker run -d \
            -p 9000:9000 \
            -e MINIO_ROOT_USER=minioadmin \
            -e MINIO_ROOT_PASSWORD=minioadmin \
            minio/minio:RELEASE.2025-01-20T14-49-07Z \
            server /data

      - name: Install MinIO client
        run: |
          curl -s https://dl.min.io/client/mc/release/linux-amd64/mc -o mc
          chmod +x mc

      - name: Create bucket
        run: |
          sleep 10
          ./mc alias set local http://localhost:9000 minioadmin minioadmin
          ./mc mb --ignore-existing local/taskapi

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew integrationTest --info